apiVersion: apps/v1
kind: Deployment
metadata:
  name: grade-submission-api
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: grade-submission-api
  template:
    metadata:
      labels:
        app: grade-submission-api
    spec:
      imagePullSecrets:
      - name: ghcr-secret
      containers:
      - name: grade-submission-api
        image: ghcr.io/bola-pixel/kubernetes-cicd-tutorial:8a81bb5fa22ff2a2adad48328cf3836b6f629f28
        ports:
        - containerPort: 3000
        resources:
          limits:
            memory: "16Mi"
            cpu: "500m"
          requests:
            memory: "16Mi"
            cpu: "250m"
---
apiVersion: v1
kind: Service
metadata:
  name: grade-submission-api
  namespace: default
spec:
  selector:
    app: grade-submission-api
  ports:
  - port: 80
    targetPort: 3000
  type: ClusterIP
