apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - deployment.yaml
  - service.yaml

images:
  - name: ghcr.io/bola-pixel/kubernetes-cicd-tutorial
    newTag: ec37b2c5b5110c6919cd7cd1e561ab541af1b78e
