apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- deployment.yaml
- service.yaml

images:
- name: ghcr.io/bola-pixel/kubernetes-cicd-tutorial
  newName: ghcr.io/bola-pixel/kubernetes-cicd-tutorial
  newTag: ddb7beb52b34249dbd61fb5c5e23fe4c990fbfb2
